version: '3.8'

services:
  axiom:
    image: ghcr.io/brunovnunes/axiom:latest   # <-- essa linha substitui o build
    container_name: axiom-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    command: ["node", "dist/api/server.js", "--orchestrator"]